version: '3.7'

services:
  app_nginx:
    image: nginx
    depends_on:
      - app_fpm
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx:/etc/nginx/conf.d

  app_fpm:
    build:
      context: ./docker
      dockerfile: Dockerfile-fpm
      target: dev
    environment:
      - PHP_IDE_CONFIG=serverName=appName
      - XDEBUG_CONFIG=remote_enable=1 remote_host=172.17.0.1 remote_port=9000 idekey=PHPSTORM
    volumes:
      - ./app:/var/www/app