FROM php:7.4-fpm-alpine AS prod

RUN apk update && apk upgrade


FROM prod as dev

RUN apk add --no-cache --update --virtual buildDeps $PHPIZE_DEPS \
    && pecl install xdebug-2.9.5 \
    && docker-php-ext-enable xdebug \
    && apk del --purge buildDeps

WORKDIR /var/www/app